{
    "swagger": "2.0",
    "info": {
        "title": "PropertyPro-Lite APi",
        "version": "1.0.0",
        "description": "Property Pro Lite is a platform where people can create and/or search properties for sale or rent.",
        "contact": "solomonfrank73@hotmail.com",
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        }
    },
    "host": "propertyprolite-app.herokuapp.com",
    "basepath": "",
    "securityDefinitions": {
        "Authorization": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "name": "user",
            "description": "API for user entity"
        },
        {
            "name": "property",
            "description": " API for property entity"
        },
        {
            "name": "Flag",
            "description": "API for flag entity"
        }
    ],
    "schemes": [
        "https",
        "http"
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/auth/signin": {
            "post": {
                "tags": [
                    "user"
                ],
                "summary": "sign in user",
                "description": "User can login using this endpoint.",
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "description": "Login user object",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/loginModel"
                        }
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "successfully loggedin",
                        "schema": {
                            "type": "object",
                            "example": {
                                "status": "success",
                                "data": {
                                    "id": 2,
                                    "first_name": "test",
                                    "last_name": "est",
                                    "email": "test6@yahoo.com",
                                    "phone_number": "0808877447",
                                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOnsiaWQiOjJ9LCJpYXQiOjE1NjIyNTcyNDh9.5tpZf5CTJU31Tl6tvDmfqlCJgxxLfWi92htf6Ok21IU",
                                    "address": "5 hillary street",
                                    "created_at": "2019-06-29T15:22:03.415Z",
                                    "is_admin": "false",
                                    "state": "Festac Lagos"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "example": {
                                "status": "error",
                                "error": "internal server error"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "example": {
                                "status": "error",
                                "error": "invalid email address"
                            }
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "tags": [
                    "user"
                ],
                "summary": " user can sign up",
                "description": "User can signup using this endpoint.",
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "description": "User's should be able to sign up",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/signUpModel"
                        }
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "201": {
                        "description": " signup was successful",
                        "schema": {
                            "type": "object",
                            "example": {
                                "status": "success",
                                "data": {
                                    "email": "test9@yahoo.com",
                                    "password": "1234567",
                                    "first_name": "test",
                                    "last_name": "test",
                                    "phone_number": "male",
                                    "address": "Festac Lagos",
                                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9",
                                    "created_at": "2019-06-29T15:22:03.415Z",
                                    "country": "Nigeria"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "example": {
                                "status": "error",
                                "error": "Email already exist"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server error",
                        "example": {
                            "status": "error",
                            "error": "internal server error"
                        }
                    }
                }
            }
        },
        "/property": {
            "post": {
                "tags": [
                    "property"
                ],
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "summary": "user can create propery",
                "consumes": "multipart/form-data",
                "description": "User can property  using this endpoint.",
                "parameters": [
                    {
                        "in": "formData",
                        "name": "image_url",
                        "type": "file",
                        "required": true
                    },
                    {
                        "in": "formData",
                        "name": "token",
                        "type": "string",
                        "required": true
                    },
                    {
                        "in": "formData",
                        "name": "price",
                        "type": "string",
                        "required": true
                    },
                    {
                        "in": "formData",
                        "name": "state",
                        "type": "string",
                        "required": true
                    },
                    {
                        "in": "formData",
                        "name": "city",
                        "type": "string",
                        "required": true
                    },
                    {
                        "in": "formData",
                        "name": "address",
                        "type": "string",
                        "required": true
                    },
                    {
                        "in": "formData",
                        "name": "type",
                        "type": "string",
                        "required": true
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "201": {
                        "description": "property successfully created",
                        "schema": {
                            "type": "object",
                            "example": {
                                "status": "success",
                                "data": {
                                    "id": 2,
                                    "owner": 2,
                                    "status": "available",
                                    "price": 52525,
                                    "state": "Lagos",
                                    "city": "Lagos",
                                    "address": "Lagos",
                                    "type": "2bedroom",
                                    "owner_email": "test6@yahoo.com",
                                    "created_on": "2019-07-05T11:03:03.044Z",
                                    "image_url": "http://res.cloudinary.com/test6test/image/upload/v1563688855/fbkp5kxv3jp6byfgtsor.jpg"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "example": {
                            "stutus": "error",
                            "error": "internal server error"
                        }
                    },
                    "403": {
                        "description": "Bad Request",
                        "example": {
                            "status": "error",
                            "error": "you are not authorize to access the page"
                        }
                    }
                }
            },
            "get": {
                "tags": [
                    "property"
                ],
                "summary": "user can view all propery",
                "description": "User can property all using this endpoint.",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "loaded was successfully",
                        "schema": {
                            "type": "object",
                            "example": [
                                {
                                    "status": 200,
                                    "data": {
                                        "id": 2,
                                        "owner": 2,
                                        "status": "available",
                                        "price": 52525,
                                        "state": "Lagos",
                                        "city": "Lagos",
                                        "address": "Lagos",
                                        "type": "2bedroom",
                                        "ownerEmail": "test6@yahoo.com",
                                        "created_on": "2019-07-05T11:03:03.044Z"
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error"
                    },
                    "404": {
                        "description": "Result not found"
                    }
                }
            }
        },
        "/property/{id}": {
            "get": {
                "tags": [
                    "property"
                ],
                "summary": "user can view a specific propery",
                "description": "User can view specific property using this endpoint.",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "required": true
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "search was successful",
                        "schema": {
                            "type": "object",
                            "example": {
                                "status": 200,
                                "data": {
                                    "id": 2,
                                    "owner": 2,
                                    "status": "available",
                                    "price": 52525,
                                    "state": "Lagos",
                                    "city": "Lagos",
                                    "address": "Lagos",
                                    "type": "2 bedroom",
                                    "owner_email": "test6@yahoo.com",
                                    "created_on": "2019-07-05T11:03:03.044Z"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "example": {
                            "status": "error",
                            "error": "internal server error"
                        }
                    },
                    "404": {
                        "description": "Result not found",
                        "example": {
                            "status": "error",
                            "error": "internal server error"
                        }
                    }
                }
            },
            "patch": {
                "tags": [
                    "property"
                ],
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "summary": "user can update propertry details",
                "description": "User can update details of the property  using this endpoint.",
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "required": true,
                        "schema": {
                            "type": "objects",
                            "properties": {
                                "price": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    {
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "type": "string"
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "property successfully updated",
                        "schema": {
                            "type": "object",
                            "example": {
                                "status": 201,
                                "data": {
                                    "id": 2,
                                    "owner": 2,
                                    "status": "available",
                                    "price": 52525,
                                    "state": "Lagos",
                                    "city": "Lagos",
                                    "address": "Lagos",
                                    "type": "2bedroom",
                                    "ownerEmail": "test6@yahoo.com",
                                    "created_on": "2019-07-05T11:03:03.044Z"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/property/{id}/sold": {
            "patch": {
                "tags": [
                    "property"
                ],
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "summary": "user can update  property status",
                "description": "User can update property status using this endpoint.",
                "parameters": [
                    {
                        "in": "path",
                        "required": true,
                        "type": "string",
                        "name": "id"
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "loaded was successfully",
                        "schema": {
                            "type": "object",
                            "example": [
                                {
                                    "status": 200,
                                    "data": {
                                        "id": 2,
                                        "owner": 2,
                                        "status": "available",
                                        "price": 52525,
                                        "state": "Lagos",
                                        "city": "Lagos",
                                        "address": "Lagos",
                                        "type": "2bedroom",
                                        "owner_email": "test6@yahoo.com",
                                        "created_on": "2019-07-05T11:03:03.044Z",
                                        "image_url": "http://res.cloudinary.com/test6test/image/upload/v1563688855/fbkp5kxv3jp6byfgtsor.jpg"
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "example": {
                            "status": "error",
                            "error": "internal server error"
                        }
                    },
                    "404": {
                        "description": "Result not found",
                        "example": {
                            "status": "error",
                            "error": "internal server error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "loginModel": {
            "type": "objects",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "createPropertyModel": {
            "type": "objects",
            "properties": {
                "status": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "address": {
                    "type": "string"
                }
            }
        },
        "signUpModel": {
            "type": "objects",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "address": {
                    "type": "string"
                }
            }
        },
        "loginOutput": {
            "type": "object",
            "properties": {
                "status": "string",
                "data": "object"
            }
        }
    }
}